fix: add Typescript types
fram-x/FluidTransitions pull request #186
Opened 2019-04-24 08:17 UTC by jaulz

It would be great if someone could cross check these types 😊

2019-04-27 05:16 UTC, jarvisluong requested changes
Awesome! There are just a couple of small changes that I proposed!

2019-04-27 05:16 UTC, jarvisluong commented on lib/index.d.ts
> +import { NavigationRouteConfigMap, StackNavigatorConfig } from 'react-navigation';
```suggestion
import { NavigationRouteConfigMap, StackNavigatorConfig, NavigationContainer  } from 'react-navigation';
```

2019-04-27 05:16 UTC, jarvisluong commented on lib/index.d.ts
> +): any;
```suggestion
): NavigationContainer;
```
as similar as in https://github.com/react-navigation/react-navigation/blob/542122794ad36d9ae68f33a453e31563147280bb/typescript/react-navigation.d.ts#L938

2019-04-27 06:19 UTC, jarvisluong commented
@chrfalch I think this ts def is good, when would it be merged? I also have some project using ts and ultilizing this library 😁

2019-04-28 16:57 UTC, chrfalch commented
Thanks, @jaulz and @jarvisluong ! I'll try to get this merged and published in the next few days!

2019-04-29 20:24 UTC, altruisticsoftware commented
YES YES YES

2019-04-30 06:41 UTC, merged

2019-05-01 09:30 UTC, jaulz commented
@chrfalch thanks!